CREATE DATABASE IF NOT EXISTS accounts_service;
CREATE DATABASE IF NOT EXISTS cart_service;
CREATE DATABASE IF NOT EXISTS products_service;
CREATE DATABASE IF NOT EXISTS orders_service;
CREATE DATABASE IF NOT EXISTS payments_service;